# Generated by Django 4.1.4 on 2022-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=122)),
                ("email1", models.CharField(max_length=122)),
                ("phone1", models.CharField(max_length=122)),
                (
                    "right",
                    models.ImageField(blank=True, null=True, upload_to="shop/images"),
                ),
                (
                    "left",
                    models.ImageField(blank=True, null=True, upload_to="shop/images"),
                ),
            ],
        ),
    ]
