# Generated by Django 4.1.4 on 2022-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_email_dr_email1_rename_name_dr_name1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dr",
            name="age",
            field=models.CharField(default="", max_length=122),
        ),
        migrations.AddField(
            model_name="dr",
            name="gender",
            field=models.CharField(default="", max_length=122),
        ),
    ]
