# Generated by Django 4.1.4 on 2022-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_dr_age_dr_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="dr",
            name="lpredict",
            field=models.CharField(default="", max_length=122),
        ),
        migrations.AddField(
            model_name="dr",
            name="rprediict",
            field=models.CharField(default="", max_length=122),
        ),
    ]
